name: Security audit
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions: read-all

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
        - uses: golang/govulncheck-action@v1
          with:
            go-version-input: 1.24
            go-package: ./...
